version : 0.0

files:
  - source: /
    target: /home/ec2-user/chat-app
hooks:
  BeforeInstall:
    - location: scripts/server_clear.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: scripts/fix_privileges.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/server_start.sh
      timeout: 20
      runas: ec2-user
  ApplicationStop:
    - location: scripts/server_stop.sh
      timeout: 20
      runas: ec2-user
