server:
  port: 9091
jwt_secret: nagarajujunnaadwikaayanshswethavarunkumarsreen22221dsdsdsdsdsdsdsdsdsdsd

spring:
  datasource:
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    url: jdbc:mysql://${MYSQL_URL}:3306/chat-app
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  security:
    user:
      name: user
      password: user
  main:
    allow-bean-definition-overriding: true
  config:
    activate:
      on-profile: aws